<?php

namespace CoreSys\UserBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends EntityRepository
{

    /**
     * Get the new users withing a set number of days
     *
     * @param int $days
     *
     * @return array
     */
    public function getNewUsers( $days = 7 )
    {
        $date = new \DateTime();
        $date = $date->sub( new \DateInterval( 'P' . intval( $days ) . 'D' ) );
        $q    = $this->createQueryBuilder( 'u' )
                ->where( 'u.created_at >= :date' )
                ->setParameter( 'date', $date )
                ->orderBy( 'u.created_at', 'desc' )
                ->getQuery();

        return $q->getResult();
    }

    /**
     * Get active/inactive or all users
     *
     * @param null|bool $active
     *
     * @return array
     */
    public function getUsers( $active = NULL )
    {
        $q = $this->createQueryBuilder( 'u' )
             ->orderBy( 'u.created_at', 'desc' );

        if ( $active === TRUE || $active == FALSE ) {
            $q->where( 'u.enabled = :active' )
            ->setParameter( 'active', $active );
        }

        $q = $q->getQuery();

        return $q->getResult();
    }
}
